name: build

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install gperf
        run: |
          sudo apt-get update
          sudo apt-get install -y gperf

      - name: Cache Td lib
        uses: actions/cache@v4
        with:
          path: build/td
          key: lib-${{ runner.os }}-${{ hashFiles('td/**') }}
          retention-days: 30

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel
